# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-12-09 11:07:27
"""
import arcpy

def Model():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    comm_2_ = "comm"
    mainriversclip = "mainriversclip"
    commandmainriversjoin_3_ = "commandmainriversjoin"
    namedriversclip = "namedriversclip"
    commandmainriversandnamedriversjoin_3_ = "ModelBuilder\\commandmainriversandnamedriversjoin"
    seaoutletclip = "seaoutletclip"
    commandmainriversandnamedriversandseaoutletjoin_3_ = "ModelBuilder\\commandmainriversandnamedriversandseaoutletjoin"
    islandclip = "islandclip"
    main_NaturaSite_polygon = "main.NaturaSite_polygon"
    split_dalmatia_county_border = "split_dalmatia_county_border"
    alljoinscommmainrivernamedriversseaoutletisland_2_ = "alljoinscommmainrivernamedriversseaoutletisland"
    natura2000_2_ = "natura2000"
    marine = "marine"
    split_dalmatia_county_border_2_ = "split_dalmatia_county_border"
    alljoinscommmainrivernamedriversseaoutletislandandnature2_2_ = "alljoinscommmainrivernamedriversseaoutletislandandnature2"
    marineclip_2_ = "marineclip"
    naturaclip2000_3_ = "naturaclip2000"
    marineclip_3_ = "marineclip"
    marineclip_4_ = "marineclip"
    main_HABITATS = "main.HABITATS"
    naturaclip2000 = "naturaclip2000"
    main_alljoinscommmainrivernamedriversseaoutletislandgpkg_2_ = "main.alljoinscommmainrivernamedriversseaoutletislandgpkg"
    main_naturemarinejoingpkg = "main.naturemarinejoingpkg"
    alljoinscommmainrivernamedriversseaoutletisland_3_ = "alljoinscommmainrivernamedriversseaoutletisland"
    naturemarinejoin = "naturemarinejoin"
    naturemarinejoin_3_ = "naturemarinejoin"
    alljoinscommmainrivernamedriversseaoutletisland = "alljoinscommmainrivernamedriversseaoutletisland"

    # Process: Add Join (Add Join) (management)
    commandmainriversjoin = arcpy.management.AddJoin(in_layer_or_view=comm_2_, in_field="OBJECTID", join_table=mainriversclip, join_field="OBJECTID")[0]

    # Process: Add Join (2) (Add Join) (management)
    commandmainriversandnamedriversjoin = arcpy.management.AddJoin(in_layer_or_view=commandmainriversjoin_3_, in_field="comm.OBJECTID", join_table=namedriversclip, join_field="OBJECTID")[0]

    # Process: Add Join (3) (Add Join) (management)
    commandmainriversandnamedriversandseaoutletjoin = arcpy.management.AddJoin(in_layer_or_view=commandmainriversandnamedriversjoin_3_, in_field="comm.OBJECTID", join_table=seaoutletclip, join_field="OBJECTID")[0]

    # Process: Add Join (4) (Add Join) (management)
    commandmainriversandnamedriversandseaoutletandisalndjoin = arcpy.management.AddJoin(in_layer_or_view=commandmainriversandnamedriversandseaoutletjoin_3_, in_field="comm.OBJECTID", join_table=islandclip, join_field="OBJECTID")[0]

    # Process: Clip (Clip) (analysis)
    natura2000 = "C:\\Users\\lartey\\OneDrive - Stichting Deltares\\Desktop\\DesirMED Work_Together\\1 Project Data\\1 Land Use_Processed\\Governance\\intersects\\intersects.gdb\\natura2000"
    arcpy.analysis.Clip(in_features=main_NaturaSite_polygon, clip_features=split_dalmatia_county_border, out_feature_class=natura2000)

    # Process: Add Join (5) (Add Join) (management)
    alljoinscommmainrivernamedriversseaoutletislandandnature = arcpy.management.AddJoin(in_layer_or_view=alljoinscommmainrivernamedriversseaoutletisland_2_, in_field="OBJECTID", join_table=natura2000_2_, join_field="OBJECTID")[0]

    # Process: Clip (2) (Clip) (analysis)
    marineclip = "C:\\Users\\lartey\\OneDrive - Stichting Deltares\\Desktop\\DesirMED Work_Together\\1 Project Data\\1 Land Use_Processed\\Governance\\intersects\\intersects.gdb\\marineclip"
    arcpy.analysis.Clip(in_features=marine, clip_features=split_dalmatia_county_border_2_, out_feature_class=marineclip)

    # Process: Add Join (6) (Add Join) (management)
    alljoinscommmainrivernamedriversseaoutletislandandnature2andmarine = arcpy.management.AddJoin(in_layer_or_view=alljoinscommmainrivernamedriversseaoutletislandandnature2_2_, in_field="OBJECTID", join_table=marineclip_2_, join_field="alljoinscommmainrivernamedriversseaoutletisland.OBJECTID")[0]

    # Process: Add Join (7) (Add Join) (management)
    naturaclip2000_2_ = arcpy.management.AddJoin(in_layer_or_view=naturaclip2000_3_, in_field="OBJECTID", join_table=marineclip_3_, join_field="OBJECTID", index_join_fields="INDEX_JOIN_FIELDS")[0]

    # Process: Add Join (8) (Add Join) (management)
    nowalljoincomplete = arcpy.management.AddJoin(in_layer_or_view=main_alljoinscommmainrivernamedriversseaoutletislandgpkg_2_, in_field="fid", join_table=main_naturemarinejoingpkg, join_field="fid", index_join_fields="INDEX_JOIN_FIELDS")[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\Users\\lartey\\OneDrive - Stichting Deltares\\Documents\\ArcGIS\\Projects\\MyProject1.gdb", workspace="C:\\Users\\lartey\\OneDrive - Stichting Deltares\\Documents\\ArcGIS\\Projects\\MyProject1.gdb"):
        Model()
